services:
  verity-bot:
    container_name: verity-bot
    image: verity-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    restart: unless-stopped
    init: true
    environment:
      NODE_ENV: production
      TZ: ${TZ:-Europe/London}
      DISCORD_TOKEN: ${DISCORD_TOKEN:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_ADMIN_KEY: ${OPENAI_ADMIN_KEY:-}
    volumes:
      - type: bind
        source: ./config.json
        target: /app/config.json
      - type: bind
        source: ./sounds
        target: /app/sounds
        read_only: true
    command: npm start
    labels:
      - homepage.group=Bots
      - homepage.name=Verity Bot
      - homepage.icon=discord.png
      - homepage.href=https://192.168.0.14:9443
      - homepage.description=Discord bot

